pkg build information updated, description and informational file used by packagemaker included in Description.plist and Info.plist respectivally. M    OSX_Resources/InstallationCheck A    OSX_Resources/Info.plist A    OSX_Resources/Description.plist

diff --git a/OSX_Resources/InstallationCheck b/OSX_Resources/InstallationCheck
--- a/OSX_Resources/InstallationCheck
+++ b/OSX_Resources/InstallationCheck
@@ -9,7 +9,7 @@ minor=`echo $version | sed 's/\([0-9]\)\.\([0-9]\)\.\([0-9]\)/\2/'`
 if test $major -lt 7 -o $major -eq 7 -a $minor -lt 9
 then
     # Warn and display message 16
-    exit 48
+    exit 112
 fi
 
 # Now check for libdap: first check that we can run the config script, then
@@ -27,6 +27,7 @@ minor=`echo $version | sed 's/\([0-9]\)\.\([0-9]\)\.\([0-9]\)/\2/'`
 
 if test $major -lt 3 -o $major -eq 3 -a $minor -lt 5
 then
+    # fail and display message 17
     exit 113
 fi
 
