Comments and reorg

diff --git a/bin/hic_ingest b/bin/hic_ingest
--- a/bin/hic_ingest
+++ b/bin/hic_ingest
@@ -27,7 +27,6 @@
 
 DRY_RUN="--dryrun"
 H5_REGEX=".*\.(HDF5|h5|he5)(\.bz2|\.gz|\.Z)?$"
-#H5_REGEX=".*\.h5$"
 EXCLUDE_REGEX="^\\..*$"
 INCLUDE_REGEX="^.*$"
 
@@ -40,17 +39,17 @@ INCLUDE_REGEX="^.*$"
 show_usage() {
 cat <<EOF
 
- Usage: $0 [h|v|V|R] [-c <bes_conf>] [-b <s3_bucket_name>] [-u <s3_profile_name>] [-r <s3_region>] [-p <parent_path>] [-i <include_regex>] [-x <exclude_regex>] <bes_catalog_root_dir>
+ Usage: $0 [h|v|V|R] [-c <bes_conf>] [-b <s3_bucket_name>] [-u <s3_profile_name>] [-r <s3_region>] [-p <parent_path>] [-s <site_map_file>] [-i <include_regex>] [-x <exclude_regex>] <bes_catalog_root_dir>
 
  -h  Print this page.
- -v  Verbose: Print the DMR too
- -V  Very Verbose: print the DMR, the command and the configuration
-     file used to build the DMR
+ -v  Verbose Lots of informative output
+ -V  Very Verbose: Even more informative output, including the bes.conf file.
  -R  Recursively process <directory>''s child directories.
  -b <s3_bucket_name> The name of the S3 bucket into which to place the files.
  -u <s3_profile_name> The name of the AWS profile to use when intracting with S3.
  -r <s3_region> The AWS region of your bucket. (?? really??)
  -p <parent_path> The parent path, relative to the BES.
+ -s <site_map_file> The file to which to write the site map of ingested files.
  -i <include_regex> A regex to match the (basename) of the files to be included.
  -c <exclude_regex> A regex to match the (basename) of the files to be excluded.
 
@@ -137,7 +136,9 @@ function qc_inputs(){
 # ingest acitvity.
 #
 # . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
-function make_bes_conf(){
+function make_bes_conf() {
+    
+    from_hyrax=0;
     
     # Find teh bes.conf file
     if [ -z ${source_bes_conf+x} ]
@@ -150,6 +151,7 @@ function make_bes_conf(){
             if [ -r $test_conf ]
             then
                 source_bes_conf="$test_conf"
+                from_hyrax=1;
             fi
         fi
     fi   
@@ -181,21 +183,49 @@ function make_bes_conf(){
             echo ""
            exit;
         fi
+        from_hyrax=1;
     fi
     
     if [ ${verbose} -eq 1 ]; then echo "source_bes_conf: ${source_bes_conf}"; fi
     
+    # Temp file
     bes_conf=$(mktemp -t bes.conf_$$)
     
-    cat ${source_bes_conf} | awk -v rootDir="${bes_catalog_root_dir}" \
-        '{ 
+    # Doctor up the bes.conf file so that teh BES.Catalog.catalog.RootDirectory is
+    # set as desired and als eliminate the BES.Include line which will bork us
+    # at runtime.
+    cat ${source_bes_conf} | awk -v rootDir="${bes_catalog_root_dir}" '{ 
             if(index($0,"BES.Catalog.catalog.RootDirectory")==1){ 
                 printf("BES.Catalog.catalog.RootDirectory=%s\n",rootDir);
             }
-            else {
+            else if(index($0,"BES.Include")==0){ 
                 print $0;
             }
-        }' > $bes_conf
+        }' > ${bes_conf};
+        
+    
+    # if we got our bes.conf from an installed Hyrax we have to get the modules
+    # configurations or tnothing is going to work.
+    if [ $from_hyrax -eq 1 ] ; then
+    
+        # We add the dap.conf first because we need it for the rest to load.
+        dap_conf=`dirname $source_bes_conf`/modules/dap.conf;
+        if [ ${verbose} -eq 1 ]; then echo "Adding ${dap_conf} to bes.conf"; fi
+        cat ${dap_conf} >> ${bes_conf};
+        
+        # Now we get all the file names
+        conf_files=`dirname $source_bes_conf`/modules/*.conf;
+        # and add each one to bes.conf
+        for conf_file in ${conf_files} ; do
+            # We skip dap.conf because we already did it.
+            if [ ${conf_file} = ${dap_conf} ]  ; then
+                if [ ${verbose} -eq 1 ]; then echo "Skipping ${conf_file}."; fi
+            else 
+                if [ ${verbose} -eq 1 ]; then echo "Adding ${conf_file}."; fi
+                cat ${conf_file} >> ${bes_conf};
+            fi
+        done
+    fi
     
     bes_conf_flag="-c ${bes_conf}"
     
@@ -205,7 +235,7 @@ function make_bes_conf(){
         echo "-----------------------------------------"
     fi
  
-}
+ }
 ###########################################################################
 
 
@@ -234,7 +264,7 @@ function process_cmdln() {
     find_parameter=
     bes_conf_flag=
     maxdepth="-maxdepth 1"
-    
+    site_map_file="siteMap.txt"
     
     while getopts "h?RvVc:b:u:r:p:i:x:" opt; do
         case "$opt" in
@@ -245,13 +275,10 @@ function process_cmdln() {
         v)
             verbose=1;
             verbose_flag="-v";
-            echo "VERBOSE=TRUE";
             ;;
         V)
             very_verbose=1;
             verbose_flag="-v";
-            echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -";
-            echo "${0} - BEGIN - verbose enabled";
             ;;
         R)
             recursive="yes";
@@ -278,9 +305,13 @@ function process_cmdln() {
         x)
             EXCLUDE_REGEX="$OPTARG";
             ;;
+        s)
+            site_map_file="$OPTARG";
+            ;;
         esac
     done
-    
+    if [ ${verbose} -eq 1 ]; then echo "${0} - BEGIN"; fi
+
     shift $((OPTIND-1))
     
     [ "$1" = "--" ] && shift
@@ -308,9 +339,11 @@ function process_cmdln() {
 #
 # . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
 
-
+            
 # Process the commandline parameters.
 process_cmdln "$@";
+
+
 
 # Make sure we didn't get garbage
 qc_inputs
@@ -318,8 +351,8 @@ qc_inputs
 # Hack the bes.conf so that we use our catalog root.
 make_bes_conf
 
-# Find all the files in the tree (We might want to shift the regex application
-# to here if the size gets too big)
+# Find all the files in the tree (We might want to apply the include regex 
+# here if the size gets too big)
 file_list=`find ${bes_catalog_root_dir} ${maxdepth} -type f`;
 
 if [ ${verbose} -eq 1 ]; then echo "Found "`echo ${file_list} | wc -w`" files."; fi
@@ -357,16 +390,30 @@ do
         if [ ${verbose} -eq 1 ]; then echo "mds_cmd: ${mds_cmd}"; fi
         if [ -z ${DRY_RUN} ] || [ true ] ; then
             $mds_cmd;
+            mds_status=$?;
+            if [ ${mds_status} -ne 0 ]; then
+                echo "MDS INGEST FAILED. STATUS: ${mds_status}";
+            fi
         fi
         
         # This is the command that will copy the file to the S3 bucket.
         aws_cmd="aws s3 cp ${DRY_RUN} "${afile}" s3://${s3_bucket_name}/$logical_path"
         if [ ${verbose} -eq 1 ]; then echo "aws_cmd: ${aws_cmd}"; fi
         $aws_cmd;
-                
+        aws_status=$?;
+        if [ ${aws_status} -ne 0 ]; then
+            echo "AWS UPLOAD FAILED. STATUS: ${aws_status}";
+        fi
+        
+        if [ ${mds_status} -eq 0 ] && [ ${aws_status} -eq 0 ] ; then
+            if [ ${verbose} -eq 1 ]; then echo "Adding ${logical_path} to siteMap"; fi
+            echo "${logical_path}" >> ${site_map_file};
+        fi
+              
     fi
     
 done
+if [ ${verbose} -eq 1 ]; then echo "${0} - END"; fi
 ###########################################################################
 
  
