sync

diff --git a/bin/p18-2-test-harness b/bin/p18-2-test-harness
--- a/bin/p18-2-test-harness
+++ b/bin/p18-2-test-harness
@@ -1165,21 +1165,29 @@ function testit(){
             
             if [ -z ${ce} ] || [ true ] ; then
                 echo "Not checking DAP2 data response for entire dataset, takes too long.";
-                cat  foo.${response} | grep "message = ";
                 
             elif [ "${response}" = "${dap2_data_response}" ] ; then
                 
-                echo "Checking DAP2 data response with getdap.";
-                content_lines=`cat foo.${response} | wc -l`;
-                content_lines=`echo ${content_lines}-${http_hdr_length} | bc`;
-                tail -n ${content_lines} foo.${response} > foo.${response}.body;
-                getdap -D -M foo.${response}.body > /dev/null;
-                status=$?;
+                if [ true ] ; then
+                    echo "** Performing crude error check with grep:";
+                    cat  foo.${response} | grep "message = ";
+                    echo "** Last 3 bes.log entries:";
+                    tail -n 3 /home/centos/hyrax/build/var/bes.log;
+                else 
+                    echo "** Performing full DAP2 data integrity check with getdap.";
+                    content_lines=`cat foo.${response} | wc -l`;
+                    content_lines=`echo ${content_lines}-${http_hdr_length} | bc`;
+                    tail -n ${content_lines} foo.${response} > foo.${response}.body;
+                    getdap -D -M foo.${response}.body > /dev/null;
+                    status=$?;
+                fi
+                
                 if [ ${status} -ne 0 ] ; then 
                     echo "ERROR! Unable to read dap2 data response."; 
                 else
                     echo "DAP2 Request appears to have worked.";
                 fi
+                
             else
                 echo "NO QC OF RESPONSE PERFORMED ON: ${curl_cmd}";
             fi
