Tests for the get_dmrpp application. (#596)
* Starter kit baselines and config for get_dmrpp tests

* testing

* Just DMR test

* travis hack to get verbose builrd. experiement

* Switchoing get_dmrpp from /bin/sh to /bin/bash

* Improved baseline/test filtering

* Added fully qualified get_dmrpp invocation using abs_top_builddir to locate get_dmrpp

* Added fully qualified get_dmrpp invocation using abs_top_builddir to locate get_dmrpp

* Ensure get_dmrpp is executabe

* Ensure get_dmrpp is executabe

* Fix path for besstandalone and get_dmrpp

* Fix path for besstandalone and get_dmrpp

* Fix path for besstandalone and get_dmrpp

* Hardwiored verbose mode for get_dmrpp m4 code.

* Hardwired verbose mode for get_dmrpp m4 code. - take 2

* Hardwired verbose mode for get_dmrpp m4 code. - take 2

* Reorder test buids. Verbose in m4 m,acros

* small fix for verbose

* WIP - make check works, make distcheck does not

* Added get_dmrpp.conf.in to EXTRA_DIST in dmrpp_module/data

* Added baselines and fixed sed regex

The sed regex did not match pathnames that include version numbers like
-x.y.z

* Added get_drmpp.conf to DISTCLEAN

* Renamed get_dmrpp.conf.in to get_dmrpp_mkcheck.conf.in and get_dmrpp.conf to get_dmrpp_mkcheck.conf

* Renamed get_dmrpp.conf.in to get_dmrpp_mkcheck.conf.in and get_dmrpp.conf to get_dmrpp_mkcheck.conf

* Consolidated build/install/test configurations for get_dmrpp

* Specifying build_dmrpp location for M4 macros

* Entangling paths

* Removed AUTOTES verbose flag from build.

* Dropping unneeded get_dmrpp_mkcheck.conf.in file

* Adding mkdchk, a low output 'make distcheck' invoker

Co-authored-by: James Gallagher <jgallagher@opendap.org>

diff --git a/modules/dmrpp_module/data/get_dmrpp.in b/modules/dmrpp_module/data/get_dmrpp.in
--- a/modules/dmrpp_module/data/get_dmrpp.in
+++ b/modules/dmrpp_module/data/get_dmrpp.in
@@ -1,8 +1,27 @@
-#!/bin/sh
+#!/bin/bash
 set -e
 #set -x;
 
 GET_DMRPP_VERSION="get_dmrpp-@get_dmrpp_version@";
+
+function mk_automake_conf() {
+    local config_doc=$(
+    cat <<EOF
+# -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
+# These are the buildir libraries used for running make check/distcheck
+BES.module.dap=@abs_top_builddir@/dap/.libs/libdap_module.so
+BES.module.cmd=@abs_top_builddir@/xmlcommand/.libs/libdap_xml_module.so
+BES.module.h5=@abs_top_builddir@/modules/hdf5_handler/.libs/libhdf5_module.so
+BES.module.dmrpp=@abs_top_builddir@/modules/dmrpp_module/.libs/libdmrpp_module.so
+BES.module.nc=@abs_top_builddir@/modules/netcdf_handler/.libs/libnc_module.so
+BES.module.fonc=@abs_top_builddir@/modules/fileout_netcdf/.libs/libfonc_module.so
+# -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
+EOF
+    )
+  if test -n "$verbose"; then echo "${config_doc}" >&2 ; fi
+  echo "${config_doc}"
+}
+
 
 ###############################################################################
 #
@@ -146,6 +165,15 @@ AllowedHosts+=^https?:\/\/
 EOF
   )
 
+  if test -n "${USE_AUTOMAKE_LIBS}"; then
+      local automake_libs=$(mk_automake_conf)
+      if test -n "${verbose}"; then
+          echo "mk_default_bes_conf() - Using automake_libs: " >&2
+          echo "${automake_libs}" >&2
+      fi
+      export BES_CONF_DOC=$(echo "${BES_CONF_DOC}"; echo "${automake_libs}");
+  fi
+
 }
 ###############################################################################
 
@@ -153,7 +181,7 @@ EOF
 #
 # Print the usage information.
 #
-show_usage() {
+function show_usage() {
     echo ""
     echo " [${GET_DMRPP_VERSION}]"
     cat <<EOF
@@ -184,7 +212,8 @@ show_usage() {
      default BES configuration. Much like the site.conf file works for the full server
      deployment it will be loaded last and the settings there-in will have an override
      effect on the default configuration.
- -o: The name of the dmr++ file to create.
+ -o: The name of the dmr++ file to create. This is required when using -U so that the
+     AWS CLI component has a file to transfer.
  -e: The name of pre-existing dmr++ file to test.
  -T: Run ALL hyrax tests on the resulting dmr++ file and compare the responses
      the ones generated by the source hdf5 file.
@@ -205,7 +234,11 @@ show_usage() {
      invocations of get_dmrpp (using -r) to identify the missing variable file.
  -U: If present, and if the input data file is an AWS S3 URL (s3://...), and if the output data file has been set (using
      the -o option) the presence of this parameter will cause get_dmrpp to copy the finished dmr++ file to the same S3
-     bucket location as the input data file.
+     bucket location as the input data file. This must be used in conjunction with the -o switch as a local file is
+     required before it can be transferred to S3.
+ -A: If present will cause the tool to use the "build" versions of the various component libraries as opposed to the
+     nominal "install" version. This option is used by the autotest (aka make check/distcheck) targets for testing
+     against builds that have not been installed.
 
  Limitations:
  * The name of the hdf5 file must be expressed relative to the BES_DATA_ROOT, or as an S3 URL (s3://...)
@@ -230,8 +263,9 @@ MASTER_SHA256=
 BES_DATA_ROOT="/tmp"
 existing_dmrpp=
 S3_UPLOAD=
+USE_AUTOMAKE_LIBS=
 
-while getopts "h?vVDu:o:c:b:s:p:r:e:zTIFMU" opt; do
+while getopts "h?vVDu:o:c:b:s:p:r:e:zTIFMUA" opt; do
   case "$opt" in
   h | \?)
     show_usage >&2
@@ -240,6 +274,9 @@ while getopts "h?vVDu:o:c:b:s:p:r:e:zTIFMU" opt; do
   z)
     echo "${GET_DMRPP_VERSION}" >&2
     exit 0
+    ;;
+  A)
+    USE_AUTOMAKE_LIBS="true"
     ;;
   v)
     verbose="yes"
@@ -442,43 +479,48 @@ EOF
 
 ########################################################################################################################
 # Prepare the bes.conf file - use external if provided otherwise use the here doc.
+# Returns the bes conf file name on stdout.
 #
 function make_bes_conf() {
 
   if test -n "${1}"; then
-    if test -n "${verbose}"; then
-      echo "Using BES Configuration: \"${1}\"" >&2
-    fi
-    BES_CONF_DOC=$(cat ${1})
+    export BES_CONF_DOC=$(cat ${1})
   else
     mk_default_bes_conf
   fi
 
-  TMP_CONF=$(mktemp -t conf_XXXX)
-  echo "${BES_CONF_DOC}" > ${TMP_CONF}
-
-  if test -n "${2}"; then
-    if test -n "${verbose}"; then
-      echo "Adding additional BES configuration from: ${2}" >&2
+    if test -n "${2}"; then
+      if test -n "${verbose}"; then
+        echo "Adding additional BES configuration from: ${2}" >&2
+      fi
+      export BES_CONF_DOC=$(echo "${BES_CONF_DOC}"; cat "${2}");
     fi
-    cat "${2}" >> ${TMP_CONF}
+#    echo "Using BES Configuration: " >&2
+#    echo "${BES_CONF_DOC}" >&2
+
+  if test -n "${verbose}"; then
+    echo "Using BES Configuration: " >&2
+    echo "${BES_CONF_DOC}" >&2
   fi
+
+  local tmp_conf_file=$(mktemp -t conf_XXXX)
+  echo "${BES_CONF_DOC}" > ${tmp_conf_file}
+
 
   if test -n "$very_verbose"; then
-    echo "TMP_CONF: ${TMP_CONF}" >&2
-    ls -l ${TMP_CONF} >&2
-    cat ${TMP_CONF} >&2
+    echo "tmp_conf_file: ${tmp_conf_file}" >&2
+    ls -l ${tmp_conf_file} >&2
+    cat ${tmp_conf_file} >&2
   fi
 
-  if test -n "$verbose"; then
-    if test -n "${2}"; then
-      echo "      site_conf: ${2}" >&2
+    if test -n "$verbose"; then
+        echo "       bes_conf: ${tmp_conf_file}" >&2
+        if test -n "${2}"; then
+            echo "      site_conf: ${2}" >&2
+        fi
     fi
-    echo "       bes_conf: ${TMP_CONF}" >&2
-  fi
 
-  echo "${TMP_CONF}"
-  unset TMP_CONF
+  echo "${tmp_conf_file}"
 }
 ########################################################################################################################
 
@@ -628,49 +670,54 @@ function ck_dmrpp() {
 #
 
 function make_missing_conf() {
-  MISSING_CONF_ELEMENTS=$(
+  local missing_conf_elements=$(
     cat <<EOF
-
-#Make sure this follows the netCDF-4 enhanced model
+# Make sure this follows the netCDF-4 enhanced model
+#
 FONc.ClassicModel=false
-
-#Don't generate global attributes since we only
-#care about the variable value information.
+#
+# Don't generate global attributes since we only
+# care about the variable value information.
+#
 FONc.NoGlobalAttrs=true
-
 H5.ForceFlattenNDCoorAttr=true
 H5.RmConventionAttrPath=true
-#We don't map 64-bit integer to DMR
-#to make it consistent with data value reading.
+#
+# We don't map 64-bit integer to DMR
+# to make it consistent with data value reading.
+#
 H5.EnableDMR64bitInt=false
-#When the HDF5 storage size is zero, Fullnamepath
-#attribute should not be generated for DMRPP to work.
+#
+# When the HDF5 storage size is zero, Fullnamepath
+# attribute should not be generated for DMRPP to work.
+#
 H5.NoZeroSizeFullnameAttr=true
-
+#
 EOF
   )
 
   if test -n "${1}"; then
     if test -n "${verbose}"; then
-      echo "Using BES Configuration: \"${1}\""
+      echo "Using Missing variable BES Configuration: \"${1}\""
     fi
-    MISSING_CONF_DOC=$(cat ${1})
+    missing_conf_elements=$(cat ${1})
   else
     mk_default_bes_conf
   fi
 
-  MISSING_CONF=$(mktemp -t conf_XXXX)
+  export BES_CONF_DOC=$(echo "${BES_CONF_DOC}"; echo "${missing_conf_elements}");
 
-  echo "${BES_CONF_DOC}" "${MISSING_CONF_ELEMENTS}" >${MISSING_CONF}
+  local missing_bes_conf_file=$(mktemp -t conf_XXXX)
+
+  echo "${BES_CONF_DOC}" >${missing_bes_conf_file}
 
   if test -n "$very_verbose"; then
-    echo "MISSING_CONF: ${MISSING_CONF}" >&2
-    ls -l ${MISSING_CONF} >&2
-    cat ${MISSING_CONF} >&2
+    echo "missing_bes_conf_file: ${missing_bes_conf_file}" >&2
+    ls -l ${missing_bes_conf_file} >&2
+    cat ${missing_bes_conf_file} >&2
   fi
 
-  echo "${MISSING_CONF}"
-  unset MISSING_CONF
+  echo "${missing_bes_conf_file}"
 
 }
 ###############################################################################
@@ -1256,7 +1303,12 @@ then
     input_data_file=$(basename "${s3_granule}")
     echo "input_data_file: ${input_data_file}" >&2
 
-    local_file="${BES_DATA_ROOT}/${input_data_file}"
+    local_file=""
+    if test "${BES_DATA_ROOT}" = "/"; then # TODO - This should test for ends_with("/")
+        local_file="/${input_data_file}"
+    else
+        local_file="${BES_DATA_ROOT}/${input_data_file}"
+    fi
     echo "Copying S3 object to: ${local_file}" >&2
 
     aws s3 cp ${s3_granule} ${local_file}
