Get dmrpp tests (#637)
* Added test for -o output_file

* Updated tests_build_dmrpp

* New baseline files

* Updated dmrpp-tests

* Updated for -U

* Updated -U test baseline file

* Updated testsuite.at to include only working tests with existing macros.m4 setup

* Removed missing-file test, broken in get_dmrpp

* Set tests_build_dmrpp testsuite verbose by default

* Adding grep to Travis machine

* Exlicit call to test for s3 check

* distcheck issues

* distcheck issues

Co-authored-by: ndp-opendap <ndp@opendap.org>
Co-authored-by: dh-opendap <dholloway@opendap.org>

diff --git a/modules/dmrpp_module/data/get_dmrpp.in b/modules/dmrpp_module/data/get_dmrpp.in
--- a/modules/dmrpp_module/data/get_dmrpp.in
+++ b/modules/dmrpp_module/data/get_dmrpp.in
@@ -951,8 +951,8 @@ function dap4_array_test() {
   var_count=$(dap4_array_counter ${dmr_file} ${type})
   if test -n "${verbose}"; then echo "Found ${var_count} variables of type ${type} in DMR: ${dmr_file}" >&2; fi
   if [ ${var_count} -lt 1 ]; then
-    echo "ERROR! No variables found in DMR!" >&2
-    return 1
+    echo "ERROR! No variables of type ${type} found in DMR!" >&2
+    return 0
   fi
 
   pick_var=$(echo "${var_count}*${RANDOM}/32767+1" | bc)
