Fixed

diff --git a/modules/dmrpp_module/data/get_dmrpp.in b/modules/dmrpp_module/data/get_dmrpp.in
--- a/modules/dmrpp_module/data/get_dmrpp.in
+++ b/modules/dmrpp_module/data/get_dmrpp.in
@@ -489,11 +489,12 @@ function mkDapRequest() {
       cat ${DAP_RESPONSE} >&2
     fi
   fi
+
   # This is the return value of the function!
   echo "${DAP_RESPONSE}"
 
   # Clean up temporary files if not in debug mode
-  if test ! -n "$verbose"; then
+  if test -z "$verbose"; then
     #echo "DAP_CMD: ${DAP_CMD}"
     #echo "BES_CONF: ${BES_CONF}"
     rm -f ${DAP_CMD} ${BES_CONF}
@@ -519,6 +520,7 @@ function mk_dmrpp() {
     echo "      dmrpp_url: ${dmrpp_url}"
     echo "    output_file: ${output_file}"
   fi
+
   if test -z "${just_dmr}"; then
     prms="${very_verbose}"
     prms="${prms} -c ${BES_CONF} "
@@ -535,11 +537,11 @@ function mk_dmrpp() {
     echo "The just_dmr flag is set, skipping dmr++ construction."
   fi
 
-  if test ! -n "$very_verbose"; then
+  #if test ! -n "$very_verbose" && test ! -n "$verbose"; then
     #echo "  mk_dmrpp:BES_CONF: ${BES_CONF}"
     #echo "mk_dmrpp:SOURCE_DMR: ${SOURCE_DMR}"
-    rm -f ${BES_CONF} ${SOURCE_DMR}
-  fi
+    #rm -f ${BES_CONF} ${SOURCE_DMR}
+  #fi
 
   # TODO Use trap to ensure these are really removed
   # rm $DMR_CMD $SOURCE_DMR $TMP_CONF
@@ -1015,6 +1017,20 @@ function dmrpp_value_test() {
 
 BES_CONF=$(make_bes_conf "${bes_conf_file}")
 SOURCE_DMR=$(mkDapRequest "${input_data_file}" dmr)
+
+# If 'just_dmr' is set redirect SOURCE_DMR to either <stdout> or $output_file
+if [ -n "${just_dmr}" ]; then
+  if [ -z "${output_file}" ]; then
+    cat ${SOURCE_DMR} >&2
+  else
+    cat ${SOURCE_DMR} >${output_file};
+    if test -z "${verbose}"; then
+      rm -f ${SOURCE_DMR}
+    fi
+  fi
+  exit 0
+fi
+
 mk_dmrpp "${input_data_file}"
 retval=$?
 #echo "retval: ${retval}";
@@ -1119,12 +1135,12 @@ if test -n "${run_value_tests}"; then
   #echo "retval: ${retval}";
 fi
 
-if test ! -n "$very_verbose"; then
+if test -z "${verbose}"; then
   if test -n "${merge_missing_vars}"; then
-    #echo "    main:MISSING_VARS_FILE: ${missing_vars_file}"
-    #echo " main:SIDECAR_MISSING_FILE: ${temp_sidecar_file}"
-    #echo "main:SIDECAR_MISSING_DMRPP: ${temp_sidecar_dmrpp}"
-    #echo "       main:TEMPSTORE_FILE: ${tempstore_file}"
+    echo "    main:MISSING_VARS_FILE: ${missing_vars_file}"
+    echo " main:SIDECAR_MISSING_FILE: ${temp_sidecar_file}"
+    echo "main:SIDECAR_MISSING_DMRPP: ${temp_sidecar_dmrpp}"
+    echo "       main:TEMPSTORE_FILE: ${tempstore_file}"
     rm -f ${missing_vars_file} ${temp_sidecar_file} ${temp_sidecar_dmrpp} ${tempstore_file}
   fi
 fi
