Zero length dmrpp bug (#987)
Added a test to make sure the output file option was used.

If the C++ build_dmrpp program returns nothing and get_dmrpp
is used without -o, the caller must test for a zero-length
DMR++ document/response (Unless we can modify build_dmrpp).

diff --git a/modules/dmrpp_module/data/get_dmrpp.in b/modules/dmrpp_module/data/get_dmrpp.in
--- a/modules/dmrpp_module/data/get_dmrpp.in
+++ b/modules/dmrpp_module/data/get_dmrpp.in
@@ -1140,7 +1140,7 @@ function dap4_attributes() {
 # The sed command:
 # - removes leading and trailing whitespace from each line
 # - removes both /> and > from each line because making the dmr++ may add chunks (a kind of metadata) to
-#   variables that had no metedata (Attributes) previously, thus their termination may legitimately change
+#   variables that had no metadata (Attributes) previously, thus their termination may legitimately change
 #   from /> to >
 # The output of the sed command is sorted to normalize changes in order caused by the creation of the dmr++.
 #
@@ -1773,7 +1773,9 @@ function main() {
         echo "# BEGIN main()" >&2
         echo "#" >&2
     fi
+
     local status=0
+
     # Here we test to see if the input file name is actually an S3 URL
     # and if it is we adjust the INPUT_DATA_FILE and go out and get the
     # object from S3.
@@ -1813,6 +1815,7 @@ function main() {
         echo "# Missing file (if needed): ${s3_local_side_car_missing_file}" >&2
         set -e
     fi
+
     if test -n "${VERBOSE}";then
         echo "#######################################################################################" >&2
         echo "# BUILDING INITIAL DMR" >&2
@@ -1849,6 +1852,12 @@ function main() {
     if test $status -ne 0; then
         echo "ERROR: mk_dmrpp() ${bes_conf_file} ${INPUT_DATA_FILE} ${dmr_file} ${OUTPUT_FILE} Failed!. status: $status" >&2
         return $status
+    fi
+
+    # At this point, return an error for a zero-length DMR++ document.
+    if test -n "${OUTPUT_FILE}" -a ! -s "${OUTPUT_FILE}"; then
+        echo "ERROR : mk_dmrpp() - The DMR++ file is zero-length. Exiting..." >&2
+        return 1
     fi
 
     # if test -n "${VERBOSE}"; then echo "main() - TEMP_FILE_LIST: ${TEMP_FILE_LIST}" >&2; fi
@@ -1920,6 +1929,7 @@ function main() {
         fi
         set -e
     fi
+
     if test -n "${VERBOSE}"; then
         echo "#######################################################################################" >&2
         if test -n "${MERGE_MISSING_VARS}"; then
@@ -1928,6 +1938,7 @@ function main() {
         echo "# END main()" >&2
         echo "#######################################################################################" >&2
     fi
+
     return 0
 }
 
