Added status checking to mkDapREquest() call to besstandalone

diff --git a/modules/dmrpp_module/data/get_dmrpp.in b/modules/dmrpp_module/data/get_dmrpp.in
--- a/modules/dmrpp_module/data/get_dmrpp.in
+++ b/modules/dmrpp_module/data/get_dmrpp.in
@@ -357,12 +357,17 @@ function mkDapRequest() {
     DAP_CMD=$(mkDAP2BesCmd ${data_path} ${dap})
     #if test -n "${verbose}"; then echo "        DAP_CMD: ${DAP_CMD}" >&2; fi
 
-    DAP_RESPONSE=$(mktemp -t dmr_XXXX)
+    DAP_RESPONSE=$(mktemp -t ${dap}_XXXX)
     #if test -n "${verbose}"; then echo "   DAP_RESPONSE: ${DAP_RESPONSE}" >&2; fi
 
     besstandalone -c ${BES_CONF} -i ${DAP_CMD} >${DAP_RESPONSE}
-    echo "${DAP_RESPONSE}"
-
+    status=$?
+    if [ ${status} -ne 0 ]; then
+        echo "ERROR! Failed to build ${dap} file!.";
+        echo "Output is here: ${DAP_RESPONSE}";
+        exit 2;
+    fi
+    
     if test -n "$very_verbose"; then
         echo "${dap}_response: ${DAP_RESPONSE} data_path: ${data_path}" >&2
     fi
