Added optional dataset inventory checking to the get_dmrpp program.

diff --git a/modules/dmrpp_module/data/get_dmrpp.in b/modules/dmrpp_module/data/get_dmrpp.in
--- a/modules/dmrpp_module/data/get_dmrpp.in
+++ b/modules/dmrpp_module/data/get_dmrpp.in
@@ -1,5 +1,5 @@
 #!/bin/bash
-set -e;
+#set -e;
 
 ###############################################################################
 #
@@ -26,7 +26,7 @@ BES.Group=group_name
 BES.LogName=./bes.log
 BES.LogVerbose=no
 
-BES.modules=dap,cmd,h5
+BES.modules=dap,cmd,h5,dmrpp
 
 # Despite the comment at the top, use the development modules for now. jhrg 5/11/18
 
@@ -37,12 +37,14 @@ BES.modules=dap,cmd,h5
 BES.module.dap=@abs_top_builddir@/dap/.libs/libdap_module.so
 BES.module.cmd=@abs_top_builddir@/xmlcommand/.libs/libdap_xml_module.so
 BES.module.h5=@abs_top_builddir@/modules/hdf5_handler/.libs/libhdf5_module.so
+BES.module.dmrpp=@abs_top_builddir@//modules/dmrpp_module/.libs/libdmrpp_module.so
 
 # The value "@hdf5_root_directory@" is replaced at run time.
 BES.Catalog.catalog.RootDirectory=@hdf5_root_directory@
 BES.Data.RootDirectory=/dev/null
 
 BES.Catalog.catalog.TypeMatch=h5:.*\.(h5|he5|nc4)(\.bz2|\.gz|\.Z)?$;
+BES.Catalog.catalog.TypeMatch+=dmrpp:.*\.(dmrpp)$;
 
 BES.Catalog.catalog.Include=;
 BES.Catalog.catalog.Exclude=^\..*;
@@ -145,13 +147,13 @@ show_usage() {
  Usage: $0 [options] <hdf5 file>
 
  Write the DMR++ for hdf5_file to stdout
- 
- By default the BES Data Root directory is set to the CWD. This 
- utility will add an entry to the bes.log specified in the 
- configuration file. The DMR++ is built using the DMR as returned 
- by the HDF5 handler, using options as set in the bes 
+
+ By default the BES Data Root directory is set to the CWD. This
+ utility will add an entry to the bes.log specified in the
+ configuration file. The DMR++ is built using the DMR as returned
+ by the HDF5 handler, using options as set in the bes
  configuration file found here.
- 
+
  -h: Show help
  -v: Verbose: Print the DMR too
  -V: Very Verbose: print the DMR, the command and the configuration
@@ -161,11 +163,13 @@ show_usage() {
  -d: Data root directory for the BES.
  -c: The path to the bes configuration file to use.
  -o: The name of the file  to create.
+ -T: Run hyrax tests on the resulting dmr++ file and compare the responses
+     the ones generated by the source hdf5 file.
 
  Limitations: 
  * The pathanme to the hdf5 file must be relative from the
-   directory where this command was run; absolute paths will not work. 
- * The build_dmrpp command must be in the CWD. 
+   directory where this command was run; absolute paths will not work.
+ * The build_dmrpp command must be in the CWD.
  * The bes conf template has to build by hand. jhrg 5/11/18
 EOF
 }
@@ -177,8 +181,9 @@ very_verbose=
 just_dmr=
 dmrpp_url=
 bes_conf_file=
+run_tests=
 
-while getopts "h?vVru:d:o:c:" opt; do
+while getopts "h?vVru:d:o:c:T" opt; do
     case "$opt" in
     h|\?)
         show_usage
@@ -209,6 +214,9 @@ while getopts "h?vVru:d:o:c:" opt; do
         ;;
     o)
         output_file="$OPTARG"
+        ;;
+    T)
+        run_tests="yes"
         ;;
     esac
 done
@@ -248,79 +256,120 @@ then
 	exit 666
 fi
 
-###############################################################################
+########################################################################################################################
+# mkBesCmd()
+# Creates a BES request document for the $dap_thing (dmr, ddx, etc)
+# from the $source_data_path file and sticks the command in a temp file.
 #
-# Build the (temporary) DMR file for the target dataset.
-#
-function get_dmr() {
-	# build the xml file
-	DATAFILE="${1}";
-	
-cmdDoc=`cat <<EOF 
+function mkBesCmd() {
+  dap=${1};
+  source_data_path="${2}";
+ BESCmd=`cat <<EOF
 <?xml version="1.0" encoding="UTF-8"?>
 <bes:request xmlns:bes="http://xml.opendap.org/ns/bes/1.0#" reqID="get_dmrpp.sh">
   <bes:setContext name="dap_explicit_containers">no</bes:setContext>
   <bes:setContext name="errors">xml</bes:setContext>
   <bes:setContext name="max_response_size">0</bes:setContext>
-  
-  <bes:setContainer name="c">$DATAFILE</bes:setContainer>
-  
+
+  <bes:setContainer name="c">${source_data_path}</bes:setContainer>
+
   <bes:define name="d" space="default">
     <bes:container name="c">
     </bes:container>
   </bes:define>
-  
-  <bes:get type="dmr" definition="d" />
-  
+
+  <bes:get type="${dap}" definition="d" />
+
 </bes:request>
+
 EOF
 `
-	TMP_CMD=$(mktemp -t get_dmr_XXXX)	
-    echo "${cmdDoc}" > $TMP_CMD
-	
-	if test -n "$very_verbose"
+  TEMP_FILE=$(mktemp -t dmr_XXXX)
+  echo "${BESCmd}" > ${TEMP_FILE}
+  echo "${TEMP_FILE}"
+
+  if test -n "$verbose"
 	then
-	    echo "TMP_CMD: $TMP_CMD"
-	    cat $TMP_CMD
-	fi
-	
-	TMP_CONF=$(mktemp -t conf_XXXX)
-	
-	
-	if  test -n "${bes_conf_file}"
+    echo "${dap}_request: ${TEMP_FILE} data_path: ${source_data_path}" >&2
+    # echo " " >&2
+  fi
+
+  # ls -l ${TEMP_FILE}
+  # cat ${TEMP_FILE}
+}
+########################################################################################################################
+
+
+
+
+
+
+
+########################################################################################################################
+# Prepare the bes.conf file - use external if provided otherwise use the here doc.
+#
+function make_bes_conf() {
+
+  if  test -n "${1}"
 	then
 		if test -n "${verbose}"; then
-		   echo "Using BES Configuration: \"${bes_conf_file}\"";
+		   echo "Using BES Configuration: \"${1}\"";
 		fi
-		BES_CONF_DOC=`cat ${bes_conf_file}`;
+		BES_CONF_DOC=`cat ${1}`;
 	fi
 
+	TMP_CONF=$(mktemp -t conf_XXXX)
 	# Use the $data_root as the BES Data Root directory - this is a trick so that the
-	# script can get a DMR using the HDF5 handler algorithm, as tweaked by the 
+	# script can get a DMR using the HDF5 handler algorithm, as tweaked by the
 	# handlers configuration parameters in the BES_CONF_DOC here document.
 	echo  "${BES_CONF_DOC}" | sed -e "s%[@]hdf5_root_directory[@]%${data_root}%" > ${TMP_CONF};
-	
+
 	if test -n "$very_verbose"
 	then
-	    echo "TMP_CONF: ${TMP_CONF}"
-	    cat ${TMP_CONF}
-	fi
-	
-	TMP_DMR_RESP=$(mktemp -t dmr_XXXX)
-	
-	# use besstandalone to get the DMR
-	besstandalone -c ${TMP_CONF} -i ${TMP_CMD} > ${TMP_DMR_RESP}
-	
-	if test -n "$verbose" || test -n "$just_dmr"
-	then
-	    echo "DMR:"
-	    cat ${TMP_DMR_RESP}
+	    echo "TMP_CONF: ${TMP_CONF}" >&2
+	    ls -l ${TMP_CONF} >&2
+	    cat ${TMP_CONF} >&2
 	fi
 
+  echo "${TMP_CONF}"
+  unset TMP_CONF;
 }
-###############################################################################
+########################################################################################################################
 
-###############################################################################
+
+
+
+
+########################################################################################################################
+# getDap()
+# Gets the passed $dap response (dmr, ddx, etc) for the file $data_path and places the reponse in a temp file.
+#
+function getDap() {
+  dap=${1};
+  data_path="${2}";
+  DAP_CMD=`mkBesCmd ${dap} "${data_path}"`
+  DAP_RESPONSE=$(mktemp -t dmr_XXXX)
+  besstandalone -c ${BES_CONF} -i ${DAP_CMD} > ${DAP_RESPONSE}
+  echo "${DAP_RESPONSE}"
+
+  if test -n "$verbose"
+	then
+    echo "${dap}_response: ${DAP_RESPONSE} data_path: ${data_path}" >&2
+  fi
+
+	if test -n "$very_verbose"
+	then
+    echo "DAP_RESPONSE: " >&2
+    cat ${DAP_RESPONSE} >&2
+	fi
+}
+########################################################################################################################
+
+
+
+########################################################################################################################
+# mk_dmrpp()
+#
 function mk_dmrpp() {
     datafile="${1}";
 	full_data_path="${data_root}/${datafile}";
@@ -332,20 +381,178 @@ function mk_dmrpp() {
 	fi
 	if test -z "${just_dmr}"
 	then
-		if test -n "$very_verbose"
-		then
-		    echo "TMP_CONF: ${TMP_CONF}"
-		    cat ${TMP_CONF}
-		fi
-	    build_dmrpp ${very_verbose} -c "${TMP_CONF}" -f "${full_data_path}" -r "${TMP_DMR_RESP}" -u "${dmrpp_url}" > "${output_file}";
+      build_dmrpp ${very_verbose} -c "${BES_CONF}" -f "${full_data_path}" -r "${TMP_DMR_RESP}" -u "${dmrpp_url}" > "${output_file}";
 	else
 	    echo "The just_dmr flag is set, skipping dmr++ construction."
 	fi
 	
 	# TODO Use trap to ensure these are really removed
-	rm $DMR_CMD $TMP_DMR_RESP $TMP_CONF
+	# rm $DMR_CMD $TMP_DMR_RESP $TMP_CONF
 }
- ###############################################################################
- 
-get_dmr  "${input_data_file}";
+########################################################################################################################
+
+########################################################################################################################
+########################################################################################################################
+########################################################################################################################
+########################################################################################################################
+########################################################################################################################
+########################################################################################################################
+########################################################################################################################
+########################################################################################################################
+########################################################################################################################
+########################################################################################################################
+
+
+########################################################################################################################
+# dap2_vars()
+# Prints a list of DAP2 DDX variable declarations found in the file $1
+# The leading and trailing whitespace is trimmed from each line, and the result is sorted.
+#
+function dap2_vars() {
+  grep -e "<Byte" \
+        -e "<Int" \
+        -e "<UInt" \
+        -e "<Float" \
+        -e "<Float" \
+        -e "<String" \
+        -e "<URL" \
+        -e "<Grid" \
+        -e "<Sequence" \
+        -e "<Structure" \
+        -e "<Array" \
+  "${1}" |  sed 's/ *$//g' | sort
+}
+########################################################################################################################
+
+
+########################################################################################################################
+# dap2_attributes()
+# Prints a list of DAP2 DDX Attribute declarations found in the file $1
+# The leading and trailing whitespace is trimmed from each line, and the result is sorted.
+#
+function dap2_attributes() {
+  grep -e "<Attribute name=" -e "<Value>" "${1}" |  sed 's/ *$//g' | sort
+}
+########################################################################################################################
+
+
+########################################################################################################################
+# dap4_attributes()
+# Prints a list of DAP4 DMR Attribute declarations found in the file $1
+# The leading and trailing whitespace is trimmed from each line, and the result is sorted.
+#
+function dap4_attributes() {
+  grep -e "<Attribute name=" -e "<Value>" "${1}" |  sed 's/ *$//g' | sort;
+}
+########################################################################################################################
+
+
+########################################################################################################################
+# dap4_vars()
+# Prints a list of DAP4 DMR variable declarations found in the file $1
+# The leading and trailing whitespace is trimmed from each line, and the result is sorted.
+#
+function dap4_vars() {
+  grep \
+    -e "<Byte" \
+    -e "<Int" \
+    -e "<UInt" \
+    -e "<Float" \
+    -e "<Float" \
+    -e "<String" \
+    -e "<URI" \
+    -e "<Enumeration" \
+    -e "<Sequence" \
+    -e "<Structure" \
+    -e "<Array" \
+    -e "<Group"  \
+    -e "<Dimension" \
+  "${1}" |  sed 's/ *$//g' | sort
+}
+########################################################################################################################
+
+
+########################################################################################################################
+# compare_files()
+# Compares two files by first applying the check_function to each file and then comparing the results of the
+# check_function using diff.
+#
+function compare_files(){
+  check_function=${1};
+  first_file=${2};
+  second_file=${3};
+  success="${4}";
+  failure="${5}";
+  if test -n "$verbose"
+  then
+    echo "compare_files() check_function: ${check_function}" >&2
+    echo "compare_files()     first_file: ${first_file}" >&2
+    echo "compare_files()    second_file: ${second_file}" >&2
+  fi
+
+  first_result=$(mktemp -t dmr_XXXX)
+  if test -n "$verbose"
+  then
+    echo "compare_files()   first_result: ${first_result}" >&2
+  fi
+  f_stuff=`${check_function}  ${first_file}`
+  echo "${f_stuff}" > ${first_result}
+
+  second_result=$(mktemp -t dmr_XXXX)
+  if test -n "$verbose"
+  then
+    echo "compare_files()  second_result: ${second_result}" >&2
+  fi
+  s_stuff=`${check_function} ${second_file}`
+  echo "${s_stuff}" > ${second_result}
+
+  retval=0;
+  diff --ignore-space-change --brief ${first_result} ${second_result}
+  if [ $? -eq 0 ]
+  then
+    echo "${success}" >&2
+  else
+    echo "${failure}" >&2
+    retval=1
+  fi
+  return ${retval};
+}
+########################################################################################################################
+
+
+########################################################################################################################
+# dmrpp_inventory_test()
+#
+function dmrpp_inventory_test(){
+  echo "       BES_CONF: '${BES_CONF}'" >&2
+  echo "SOURCE_DATAFILE: ${input_data_file}" >&2
+  echo "TARGET_DATAFILE: ${output_file}" >&2
+
+  SOURCE_DDX=`getDap ddx "${input_data_file}"`
+  TARGET_DDX=`getDap ddx "${output_file}"`
+
+  SOURCE_DMR=`getDap dmr "${input_data_file}"`
+  TARGET_DMR=`getDap dmr "${output_file}"`
+
+  compare_files dap4_vars ${SOURCE_DMR} ${TARGET_DMR} " DAP4 variables: Matched." "ERROR! DAP4 variables mismatch!"
+  compare_files dap4_attributes ${SOURCE_DMR} ${TARGET_DMR} "DAP4 Attributes: Matched." "ERROR! DAP4 Attributes mismatch!"
+
+  compare_files dap2_vars ${SOURCE_DDX} ${TARGET_DDX} " DAP2 variables: Matched." "ERROR! DAP2 variables mismatch!"
+  compare_files dap2_attributes ${SOURCE_DDX} ${TARGET_DDX} "DAP2 Attributes: Matched." "ERROR! DAP2 Attributes mismatch!"
+
+}
+
+########################################################################################################################
+########################################################################################################################
+########################################################################################################################
+########################################################################################################################
+
+BES_CONF=`make_bes_conf "${bes_conf_file}"`
+TMP_DMR_RESP=`getDap dmr "${input_data_file}"`;
 mk_dmrpp "${input_data_file}";
+
+if test -n "${run_tests}"
+then
+    dmrpp_inventory_test
+fi
+# rm -f ${SOURCE_DMR} ${SOURCE_DDX} ${TARGET_DDX} ${TARGET_DMR} ${DDX_CMD} ${DMR_CMD} ${BES_CONF}
