Cleaning up the get_dmrpp.in code by placing the missing var merge and testing activities in functions in order to reduce complexity in 'main'

diff --git a/modules/dmrpp_module/data/get_dmrpp.in b/modules/dmrpp_module/data/get_dmrpp.in
--- a/modules/dmrpp_module/data/get_dmrpp.in
+++ b/modules/dmrpp_module/data/get_dmrpp.in
@@ -1088,15 +1088,131 @@ function dmrpp_value_test() {
 # Returns non-zero if the AWS CLI is not configured
 #
 function check_aws_config() {
-    aws configure list | grep "access_key" | grep -v "<not set>"
+    aws configure list | grep "access_key" | grep -v "<not set>" > /dev/null
     ret=$?
     if test $ret != 0 ; then return $ret; fi
-    aws configure list | grep "secret_key" | grep -v "<not set>"
+    aws configure list | grep "secret_key" | grep -v "<not set>" > /dev/null
     ret=$?
     if test $ret != 0 ; then return $ret; fi
-    aws configure list | grep "region" | grep -v "<not set>"
+    aws configure list | grep "region" | grep -v "<not set>" > /dev/null
     ret=$?
     if test $ret != 0 ; then return $ret; fi
+}
+
+
+########################################################################################################################
+# merge_missing()
+#
+# This function merges the missing variables (or not, depending on the state of
+# the merge_missing_vars env var.
+#
+function merge_missing() {
+    if test -n "${merge_missing_vars}"; then
+
+      # use $PATH/check_dmrpp to query dmrpp for missing CF domain variables [requires ${output_file}; -o option]
+      ck_dmrpp
+      retval=$(echo "${retval} + ${?}" | bc)
+      #echo "retval: ${retval}";
+
+      # check-dmrpp will create missing_vars_file if there are any missing variables.
+      if test -s ${missing_vars_file}; then
+        MISSING_VARS=$(cat ${missing_vars_file})
+        if test -n "$very_verbose"; then echo "The missing vars: ${MISSING_VARS}" >&2; fi
+
+        # augment bes_conf_file with additional H5 parameters necessary to synthesize missing_variables from input_data_file.
+        BES_CONF=$(make_missing_conf "${bes_conf_file}")
+
+        # insert '_missing' into input_data_file name and use for sidecar_missing_file name
+        sidecar_missing_file="${input_data_file}.missing"
+        if test -n "$very_verbose"; then echo "  MISSING_FILE: ${sidecar_missing_file}" >&2; fi
+
+        # use besstandalone to generate sidecar_missing_file
+        MISSING_FILE_BESCMD=$(mkDapRequest "${input_data_file}" dods "${MISSING_VARS}" "${sidecar_missing_file}")
+        source_data_path="${sidecar_missing_file}"
+
+        BES_CONF=$(make_bes_conf "${bes_conf_file}" "${site_conf_file}")  # reset bes_conf_file; removing additional H5 parameters
+
+        SOURCE_DMR=$(mkDapRequest "${sidecar_missing_file}" dmr)  # use besstandalone to generate dmr for sidecar_missing_file
+        master_dmrpp_file="${output_file}"  # save original dmrpp filename
+
+        if test -n "$reduce_missing_files"; then
+          if test ! -s ${MASTER_SHA256}; then
+            output_file="${BES_DATA_ROOT}/${sidecar_missing_file}.dmrpp"
+          else
+            output_file=$(mktemp -t dmrpp_XXXX) # generate temporary dmrpp filename for sidecar_missing_file
+          fi
+        else
+          output_file=$(mktemp -t dmrpp_XXXX) # generate temporary dmrpp filename for sidecar_missing_file
+        fi
+
+        mk_dmrpp "${sidecar_missing_file}"  # use $PATH/build_dmrpp to generate dmrpp for sidecar_missing_file
+        retval=$?
+        #echo "retval: ${retval}";
+
+        missing_dmrpp_file="${output_file}"
+
+        if test -n "$reduce_missing_files"; then
+          tempstore_file=$(mktemp -t tmpstore_XXXX) # generate temporary filename for tempstore to hold missing_dmrpp info
+          if test -n "$very_verbose"; then
+            echo "missing_dmrpp_file: ${missing_dmrpp_file}" >&2;
+            echo " missing_vars_file: ${sidecar_missing_file}" >&2;
+            echo "     master_sha256: ${MASTER_SHA256}" >&2;
+            echo "         tempstore: ${tempstore_file}" >&2;
+          fi
+
+          reduce_dmrpp "${sidecar_missing_file}" # use $PATH/reduce_mdf to merge sidecar_missing_file dmrpp with master_dmrpp_file
+          retval=$?
+          #echo "reduce_dmrpp: ${retval}"
+
+          if test -s ${tempstore_file}; then # if tempstore_file is not empty then there will be temp that need to be removed.
+            temp_sidecar_dmrpp=${missing_dmrpp_file}
+            temp_sidecar_file="${BES_DATA_ROOT}/${sidecar_missing_file}"
+            missing_dmrpp_file=$(echo `awk -F'[ ]' '{print $2}' "${tempstore_file}"`)
+          fi
+
+        fi
+
+        if test -n "$very_verbose"; then
+          echo "missing_dmrpp_file: ${missing_dmrpp_file}" >&2;
+          echo " master_dmrpp_file: ${master_dmrpp_file}" >&2;
+          echo "       target_path: ${target_path}" >&2;
+          echo " missing_vars_file: ${missing_vars_file}" >&2;
+        fi
+
+        # set 'href' content to use when merging chunks from sidecar_missing_file dmrpp into master_dmrpp_file
+        if test -n "${MISSING_DATA_HREF}"; then
+          target_path=$(echo "${MISSING_DATA_HREF}")
+        else
+          target_path=$(echo "OPeNDAP_DMRpp_MISSING_DATA_ACCESS_URL")
+        fi
+
+        mg_dmrpp  # use $PATH/merge_dmrpp to merge sidecar_missing_file dmrpp with master_dmrpp_file
+        retval=$(echo "${retval} + ${?}" | bc)
+        #echo "retval: ${retval}"
+
+      else
+        echo " There are no missing variables to merge."
+      fi
+    fi
+}
+
+########################################################################################################################
+# run_tests()
+#
+# This function conditionally runs the dmr++ sanity checking tests
+#
+function run_tests(){
+    if test -n "${run_inventory_tests}"; then
+        dmrpp_inventory_test
+        retval=$(echo "${retval} + ${?}" | bc)
+        #echo "retval: ${retval}";
+    fi
+
+    if test -n "${run_value_tests}"; then
+        dmrpp_value_test
+        retval=$(echo "${retval} + ${?}" | bc)
+        #echo "retval: ${retval}";
+    fi
 }
 
 ########################################################################################################################
@@ -1142,7 +1258,6 @@ then
 fi
 
 
-
 BES_CONF=$(make_bes_conf "${bes_conf_file}" "${site_conf_file}")
 SOURCE_DMR=$(mkDapRequest "${input_data_file}" dmr)
 
@@ -1164,6 +1279,19 @@ mk_dmrpp "${input_data_file}"
 retval=$?
 #echo "retval: ${retval}";
 
+
+if test -z "${verbose}"; then
+    #if test -f "${BES_CONF}" ; then rm -f "${BES_CONF}"; fi
+    if test -f "${DAP_CMD}" ; then rm -f "${DAP_CMD}"; fi
+fi
+
+# Merge the missing variable data (conditional)
+merge_missing
+
+# Run the dmr++ tests (conditional)
+run_tests
+
+# Push the dmr++ to S3 traget (conditional)
 if test -n "${s3_granule}" && test -n "${S3_UPLOAD}"
 then
     if test -z "${output_file}"
@@ -1182,111 +1310,7 @@ then
 fi
 
 
-if test -z "${verbose}"; then
-    #if test -f "${BES_CONF}" ; then rm -f "${BES_CONF}"; fi
-    if test -f "${DAP_CMD}" ; then rm -f "${DAP_CMD}"; fi
-fi
-
-if test -n "${merge_missing_vars}"; then
-
-  # use $PATH/check_dmrpp to query dmrpp for missing CF domain variables [requires ${output_file}; -o option]
-  ck_dmrpp
-  retval=$(echo "${retval} + ${?}" | bc)
-  #echo "retval: ${retval}";
-
-  # check-dmrpp will create missing_vars_file if there are any missing variables.
-  if test -s ${missing_vars_file}; then
-    MISSING_VARS=$(cat ${missing_vars_file})
-    if test -n "$very_verbose"; then echo "The missing vars: ${MISSING_VARS}" >&2; fi
-
-    # augment bes_conf_file with additional H5 parameters necessary to synthesize missing_variables from input_data_file.
-    BES_CONF=$(make_missing_conf "${bes_conf_file}")
-
-    # insert '_missing' into input_data_file name and use for sidecar_missing_file name
-    sidecar_missing_file="${input_data_file}.missing"
-    if test -n "$very_verbose"; then echo "  MISSING_FILE: ${sidecar_missing_file}" >&2; fi
-
-    # use besstandalone to generate sidecar_missing_file
-    MISSING_FILE_BESCMD=$(mkDapRequest "${input_data_file}" dods "${MISSING_VARS}" "${sidecar_missing_file}")
-    source_data_path="${sidecar_missing_file}"
-
-    BES_CONF=$(make_bes_conf "${bes_conf_file}" "${site_conf_file}")  # reset bes_conf_file; removing additional H5 parameters
-
-    SOURCE_DMR=$(mkDapRequest "${sidecar_missing_file}" dmr)  # use besstandalone to generate dmr for sidecar_missing_file
-    master_dmrpp_file="${output_file}"  # save original dmrpp filename
-
-    if test -n "$reduce_missing_files"; then
-      if test ! -s ${MASTER_SHA256}; then
-        output_file="${BES_DATA_ROOT}/${sidecar_missing_file}.dmrpp"
-      else
-        output_file=$(mktemp -t dmrpp_XXXX) # generate temporary dmrpp filename for sidecar_missing_file
-      fi
-    else
-      output_file=$(mktemp -t dmrpp_XXXX) # generate temporary dmrpp filename for sidecar_missing_file
-    fi
-
-    mk_dmrpp "${sidecar_missing_file}"  # use $PATH/build_dmrpp to generate dmrpp for sidecar_missing_file
-    retval=$?
-    #echo "retval: ${retval}";
-
-    missing_dmrpp_file="${output_file}"
-
-    if test -n "$reduce_missing_files"; then
-      tempstore_file=$(mktemp -t tmpstore_XXXX) # generate temporary filename for tempstore to hold missing_dmrpp info
-      if test -n "$very_verbose"; then
-        echo "missing_dmrpp_file: ${missing_dmrpp_file}" >&2;
-        echo " missing_vars_file: ${sidecar_missing_file}" >&2;
-        echo "     master_sha256: ${MASTER_SHA256}" >&2;
-        echo "         tempstore: ${tempstore_file}" >&2;
-      fi
-
-      reduce_dmrpp "${sidecar_missing_file}" # use $PATH/reduce_mdf to merge sidecar_missing_file dmrpp with master_dmrpp_file
-      retval=$?
-      #echo "reduce_dmrpp: ${retval}"
-
-      if test -s ${tempstore_file}; then # if tempstore_file is not empty then there will be temp that need to be removed.
-        temp_sidecar_dmrpp=${missing_dmrpp_file}
-        temp_sidecar_file="${BES_DATA_ROOT}/${sidecar_missing_file}"
-        missing_dmrpp_file=$(echo `awk -F'[ ]' '{print $2}' "${tempstore_file}"`)
-      fi
-
-    fi
-
-    if test -n "$very_verbose"; then
-      echo "missing_dmrpp_file: ${missing_dmrpp_file}" >&2;
-      echo " master_dmrpp_file: ${master_dmrpp_file}" >&2;
-      echo "       target_path: ${target_path}" >&2;
-      echo " missing_vars_file: ${missing_vars_file}" >&2;
-    fi
-
-    # set 'href' content to use when merging chunks from sidecar_missing_file dmrpp into master_dmrpp_file
-    if test -n "${MISSING_DATA_HREF}"; then
-      target_path=$(echo "${MISSING_DATA_HREF}")
-    else
-      target_path=$(echo "OPeNDAP_DMRpp_MISSING_DATA_ACCESS_URL")
-    fi
-
-    mg_dmrpp  # use $PATH/merge_dmrpp to merge sidecar_missing_file dmrpp with master_dmrpp_file
-    retval=$(echo "${retval} + ${?}" | bc)
-    #echo "retval: ${retval}"
-
-  else
-    echo " There are no missing variables to merge."
-  fi
-fi
-
-if test -n "${run_inventory_tests}"; then
-  dmrpp_inventory_test
-  retval=$(echo "${retval} + ${?}" | bc)
-  #echo "retval: ${retval}";
-fi
-
-if test -n "${run_value_tests}"; then
-  dmrpp_value_test
-  retval=$(echo "${retval} + ${?}" | bc)
-  #echo "retval: ${retval}";
-fi
-
+# Cleanup the mess, or not (conditional)
 if test -z "${verbose}"; then
   if test -n "${merge_missing_vars}"; then
     echo "    main:MISSING_VARS_FILE: ${missing_vars_file}"
