Rewinding...

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -140,25 +140,49 @@ jobs:
     - stage: build-and-test
       name: "check"
       script:
-        - ./travis/build_and_start
         - |
+          # We use fail on error (set -e) for to building and 
+          # starting the bes.
+          set -e
+          export BES_BUILD=main
+          # - export RUNTESTFLAGS="-v"
+          export LD_LIBRARY_PATH="/home/travis/install/deps/lib:$LD_LIBRARY_PATH"
+          echo "LD_LIBRARY_PATH - $LD_LIBRARY_PATH" >&2
+          autoreconf --force --install --verbose
+          ./configure $CONFIGURE_OPTIONS --disable-dependency-tracking --prefix=$prefix --with-dependencies=$prefix/deps --enable-developer
+          make -j16
+          make install  
+          besctl start
+        - |
+          # We stop failing on error (set +e) for running 
+          # make check because we want to collect the test 
+          # logs before the job fails.
           set +e
           make check -j16
-          export test_status=$?
-          ./travis/stop_and_post_test_logs
+          test_status=$?
+        - |
+          # We use fail on error (set -e) for to building and 
+          # stopping the bes, uploading the test logs, and 
+          # acting on the error state.
+          set -e
+          besctl stop
+          TEST_LOG_INVENTORY="/tmp/bes-test-log-inventory"
+          find . \( -name "*.log" -o -name "*site_map.txt" \) -print > "$TEST_LOG_INVENTORY"
+          tar -cvzf "/tmp/bes-autotest-${TRAVIS_JOB_NUMBER}-logs.tar.gz" -T "$TEST_LOG_INVENTORY"
+          ./travis/upload-test-results.sh
+          if [ $test_status -ne 0 ]; then 
+              echo "# ERROR - 'make check' failed, exiting. $test_status: $test_status" >&2
+              exit $test_status; 
+          fi
 
     # build-and-test
-    - stage: build-and-test
+    - stage: never
       name: "distcheck"
       script:
         - export BES_BUILD=distcheck
         - autoreconf --force --install --verbose
         - ./configure $CONFIGURE_OPTIONS --disable-dependency-tracking --prefix=$prefix --with-dependencies=$prefix/deps --enable-developer
-        - |
-          set +e
-          make distcheck -j16 GZIP_ENV=--fast
-          export test_status=$?
-          ./travis/stop_and_post_test_logs
+        - make distcheck -j16 GZIP_ENV=--fast
 
     # build-and-test
     - stage: never
