*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21,7 +21,7 @@
 # 4. Macros for locating various systems (Matlab, etc.)
 # 5. Macros used to test things about the computer/OS/hardware
 #
-# $Id: configure,v 1.20 1998/11/11 17:59:11 jimg Exp $
+# $Id: configure,v 1.21 1999/01/21 04:19:53 jimg Exp $
 
 # 1. Unidata's macros
 #-------------------------------------------------------------------------
@@ -1348,11 +1348,11 @@ fi
 #define DODS_BISON_VER $bison_ver2
 EOF
 
-	    if test -n "$bison_ver2" && test $bison_ver2 -ge 124
+	    if test -n "$bison_ver2" && test $bison_ver2 -ge 125
 	    then
 		echo "$ac_t""Found bison version ${bison_ver1}." 1>&6
 	    else
-		{ echo "configure: error: Bison version: found ${bison_ver1} should be at least 1.24" 1>&2; exit 1; }
+		{ echo "configure: error: Bison version: found ${bison_ver1} should be at least 1.25" 1>&2; exit 1; }
 	    fi
 	    ;;
 	*)
