re-wrote besctl to check for beslisteners and remove pid file if orphaned. Added hyrax.in to configure.ac and Makefile.am M    configure.ac M    server/besctl.in D    server/hyrax AM   server/hyrax.in M    server/Makefile.am

diff --git a/server/besctl.in b/server/besctl.in
--- a/server/besctl.in
+++ b/server/besctl.in
@@ -9,7 +9,6 @@ fi
 exec_prefix=@exec_prefix@
 localstatedir=@localstatedir@
 bindir=@bindir@
-sysconfdir=@sysconfdir@
 
 if [ ! -f ${bindir}/besdaemon ]
 then
@@ -18,79 +17,187 @@ then
 fi
 echo "BES install directory: ${prefix}"
 
-conf=${BES_CONF}
-if [ ! -f "${conf}" ]
-then
-    conf=${sysconfdir}/bes/bes.conf
-    if [ ! -f "${conf}" ]
+###########################################################################
+#
+# Attempts to start the BES
+#
+#..........................................................................
+startBES()
+{
+    echo "Starting the BES"
+
+    findRunningBES
+    if [ $BES_RUNNING  ] 
     then
-	echo "The BES configuration file cannot be located at ${conf}"
+        echo "The BES is already running."
+    else
+	canWritePid
+	if [ $WRITE_PID ]
+	then
+	    "${bindir}"/besdaemon $otherArgs
+	    sleep 5
+	    findRunningBES
+	    if [ $BES_RUNNING ]
+	    then
+		echo "OK: Successfully started the BES"
+		cat "${localstatedir}"/run/bes.pid
+	    else
+		echo "FAILED: The BES daemon did not appear to start"
+	    fi
+	fi
+    fi
+}
+
+###########################################################################
+#
+# Attempts to stop the BES
+#
+#..........................................................................
+stopBES()
+{
+    echo "Shutting down the BES daemon"
+    findRunningBES
+    if [ $BES_RUNNING ]
+    then
+	if [ $BES_PID ]
+	then
+	    kill -INT $BES_PID
+	    sleep 5
+	    findRunningBES
+	    if [ $BES_RUNNING ]
+	    then
+		echo "Unable to stop the BES, PID: $BES_PID"
+	    else
+		echo "Successfully shut down the BES"
+	    fi
+	else
+	    echo "Not running, but pid = $BES_PID"
+	fi
+    else
+	echo "The BES daemon is not currently running"
+    fi
+}
+
+###########################################################################
+#
+# Attempt to restart the BES
+#
+#..........................................................................
+restartBES()
+{
+    stopBES
+    if [ !$BES_RUNNING ]
+    then
+	startBES
+    fi
+}
+
+###########################################################################
+#
+# Attempts to locate a running BES by using the ps command to search the 
+# process stack for running instances of the besdaemon and beslistner 
+# programs. All of the PID are collected and cached in the environment
+# vairable "BES_PID"
+#
+#..........................................................................
+findRunningBES()
+{
+    unset BES_RUNNING
+    
+    if [ -f "$localstatedir"/run/bes.pid ]
+    then
+	BES_PID=`cat "$localstatedir"/run/bes.pid | cut -d' ' -f2`
+	BESLISTENER_PID=`$PS | grep -v grep | grep $BES_PID | grep beslistener | awk '{print $2}'`
+	if [ $BESLISTENER_PID ]
+	then
+	    BES_RUNNING=1
+	else
+	    echo "BES PID file exists but process not running, cleaning up"
+	    /bin/rm -f  "$localstatedir"/run/bes.pid
+
+	    BESLISTENER_PID=`$PS | grep -v grep | grep beslistener | awk '{print $2}'`
+	    if [ $BESLISTENER_PID ]
+	    then
+		echo "BES seems to be running from a different location: $BESLISTENER_PID"
+	    fi
+	fi
+    else
+	BESLISTENER_PID=`$PS | grep -v grep | grep beslistener | awk '{print $2}'`
+	if [ $BESLISTENER_PID ]
+	then
+	    echo "BES seems to be running from a different location: $BESLISTENER_PID"
+	fi
+    fi
+}
+
+###########################################################################
+#
+# Attempts to determine if the system is using the UCB or System V version 
+# of the ps command.
+#
+#..........................................................................
+checkPS()
+{
+
+UCB_PS="ps -axww -o user,pid,command"
+SYSTEM_V_PS="ps -ef -o user,pid,comm"
+
+
+#echo "Checking ps syntax"
+
+$UCB_PS > /dev/null
+if  [ $? == 0 ]
+then 
+    PS=$UCB_PS
+    #echo "Using UCB ps syntax"
+else
+    $SYSTEM_V_PS > /dev/null 
+    if  [ $? == 0 ]
+    then 
+        PS=$SYSTEM_V_PS
+        #echo "Using System V ps syntax"
+    else
+        echo "Cannot determine a functional version of \"ps\" command. Exiting."
+        exit 1
     fi
 fi
-echo "BES configuration file: ${conf}"
+}
 
-what=$1
-shift
+###########################################################################
+#
+# Check to see if user can write the pid file
+#
+#..........................................................................
+canWritePid()
+{
+    unset WRITE_PID
 
-case $what in
-stop)
-    if [ ! -f "${localstatedir}"/run/bes.pid ]
-    then
-	echo "The BES daemon is not currently running"
-	exit 1
-    fi
-    echo "Shutting down the BES daemon"
-    (cat "$localstatedir"/run/bes.pid | cut -d' ' -f2 | xargs kill -INT) 2> /dev/null
-    ;;
-start)
     # Make sure we can write the pid file! jhrg 3/31/2007
     if [ ! -x ${localstatedir}/run ] || [ ! -w ${localstatedir}/run ]
     then
 	echo "The besctl command cannot write to ${localstatedir}/run."
 	echo "Check that the directory exists and that the user running"
 	echo "besctl has write permissions for it."
-	exit 1
-    fi
-    # Check if the process is running too and if not rm the file and start.
-    if [ -f "${localstatedir}"/run/bes.pid ]
-    then
-	echo "The BES daemon is already running"
-	cat "${localstatedir}"/run/bes.pid
-	exit 1
-    fi
-    echo "Starting the BES daemon"
-    "${bindir}"/besdaemon $*
-    sleep 5
-    if [ -f "${localstatedir}"/run/bes.pid ]
-    then
-	cat "${localstatedir}"/run/bes.pid
     else
-	echo "The BES daemon did not appear to start"
+	WRITE_PID=1
     fi
+}
+
+checkPS
+
+what=$1
+shift
+otherArgs=$*
+
+case $what in
+stop)
+    stopBES
+    ;;
+start)
+    startBES
     ;;
 restart)
-    if [ ! -f "${localstatedir}"/run/bes.pid ]
-    then
-	echo "The BES daemon is not currently running"
-	exit 1
-    fi
-    echo "Shutting down the BES daemon"
-    (cat "${localstatedir}"/run/bes.pid | cut -d' ' -f2 | xargs kill -INT) 2> /dev/null
-    sleep 5
-    if [ -f ${localstatedir}/run/bes.pid ]
-    then
-	echo "Unable to stop the BES daemon"
-	exit 1
-    fi
-    echo "Starting the BES daemon"
-    "${bindir}"/besdaemon $*
-    sleep 5
-    if [ -f "${localstatedir}"/run/bes.pid ]
-    then
-	cat "${localstatedir}"/run/bes.pid
-    else
-	echo "The BES daemon did not appear to start"
-    fi
+    restartBES
     ;;
 status)
     if [ ! -f "${localstatedir}"/run/bes.pid ]
@@ -101,24 +208,8 @@ status)
     echo "The BES daemon is currently running"
     cat "${localstatedir}"/run/bes.pid
     ;;
-config)
-    conf=${BES_CONF}
-    if [ ! -f "${conf}" ]
-    then
-	conf=${sysconfdir}/bes/bes.conf
-	if [ ! -f "${conf}" ]
-	then
-	    echo "The BES configuration file cannot be located at ${conf}"
-	    exit 1
-	fi
-    fi
-    echo ""
-    echo "**************************************************************"
-    cat "${conf}"
-    echo "**************************************************************"
-    ;;
 *)
-    echo "USAGE: besctl (start|stop|restart|status|config)"
+    echo "USAGE: besctl (start|stop|restart|status)"
     exit 1
     ;;
 esac
