More adjustments to the start of the BES.
1. Changed besctl script to check for the BES command line options. Any
changes here need to be made in daemon.cc and ServerApp.cc as well. If the
-i option is NOT passed to the script then we set -i to be the prefix used
when running configure and pass it on to the daemon. If the -c option is NOT
passed to the script then we set -c to be the -i option if specified plus
/etc/bes/bes.conf, or to the BES_CONF environment variable.

2. Updated BESServerUtils::show_usage to include the -i options, specifying
the BES installation directory.

3. Updated ServerApp.cc to look for the configuration file in -c location,
then BES_CONF location, then in the directories
/user/local/etc/bes/bes.conf, then /etc/bes/bes.conf, then
/usr/etc/bes/bes.conf.

4. Updated daemon.cc to use the -i option to look for the listener
executable and the pid file (already doing this). If -i not specified then
use the path to the daemon executable from argv[0]. If no path then look in
the current working directory.

5. Updated server/Makefile.am to not pass any -D options when building. This
cleans up the package build targets.
M    server/besctl.in
M    server/BESServerUtils.cc
M    server/daemon.cc
M    server/Makefile.am
M    server/ServerApp.cc

diff --git a/server/besctl.in b/server/besctl.in
--- a/server/besctl.in
+++ b/server/besctl.in
@@ -15,7 +15,6 @@ then
     echo "BES does not appear to be installed in ${prefix}"
     exit 1
 fi
-echo "BES install directory: ${prefix}"
 
 ###########################################################################
 #
@@ -35,14 +34,19 @@ startBES()
 	if [ $WRITE_PID ]
 	then
 	    "${bindir}"/besdaemon $otherArgs
-	    sleep 5
-	    findRunningBES
-	    if [ $BES_RUNNING ]
+	    if [ $? != 0 ]
 	    then
-		echo "OK: Successfully started the BES"
-		cat "${localstatedir}"/run/bes.pid
-	    else
 		echo "FAILED: The BES daemon did not appear to start"
+	    else
+		sleep 5
+		findRunningBES
+		if [ $BES_RUNNING ]
+		then
+		    echo "OK: Successfully started the BES"
+		    cat "${localstatedir}"/run/bes.pid
+		else
+		    echo "FAILED: The BES daemon did not appear to start"
+		fi
 	    fi
 	fi
     fi
@@ -193,6 +197,73 @@ checkPS
 what=$1
 shift
 otherArgs=$*
+
+###########################################################################
+#
+# Check for the BES command line options
+# Any changes made here also need to be changed in daemon.cc and
+# ServerApp.cc
+#
+#..........................................................................
+dashi="no"
+dashc="no"
+args=`getopt hvsd:c:p:u:i: $*`
+if [ $? != 0 ]
+then
+    echo 'Usage: ...'
+    exit 2
+fi
+set -- $args
+
+for param
+do
+    case $param in
+	-i)
+	    prefix=$2
+	    localstatedir=${prefix}/var
+	    bindir=${prefix}/bin
+	    dashi="yes"
+	    shift
+	    shift
+	    ;;
+	-c)
+	    dashc=$2
+	    shift
+	    shift
+	    ;;
+	-d|-p|-u)
+	    shift
+	    shift
+	    ;;
+	-h|-v|-s)
+	    shift
+	    ;;
+	--)
+	    shift
+	    break;;
+    esac
+done
+
+echo "BES install directory: ${prefix}"
+
+if [ "$dashi" == "no" ]
+then
+    otherArgs="${otherArgs} -i ${prefix}"
+fi
+
+if [ "$dashc" == "no" ]
+then
+    if [ $BES_CONF ]
+    then
+	echo "BES configuration file: ${BES_CONF}"
+	otherArgs="${otherArgs} -c ${BES_CONF}"
+    else
+	echo "BES configuration file: ${prefix}/etc/bes/bes.conf"
+	otherArgs="${otherArgs} -c ${prefix}/etc/bes/bes.conf"
+    fi
+else
+    echo "BES configuration file: $dashc"
+fi
 
 case $what in
 stop)
