Reorganization of the bescmd files and minor changes to the bash scripts
...with an eye toward being able to run these independently and making
the result(s) a little easier to understand.

diff --git a/timing/timeTest b/timing/timeTest
--- a/timing/timeTest
+++ b/timing/timeTest
@@ -1,45 +1,64 @@
 #!/bin/bash
+#
+# Run timing tests and collect stats for the BES.
+# Given one or more bes command files (XML), for each one run it 
+# 'reps' times (default is 10) saving the output to $command.log
+# and the result to $command.result. Note that only the last result
+# is actually saved and that the log files from a previous run
+# - possibly hard won data - are silently removed.
+#
+# options: -r: number of reps
 
-reps=2
+# defaults
 
+reps=10
+
+# do the options thing...
+
+args=`getopt "r:" $*`
+if test $? != 0
+then
+	echo "Usage: timeTest [-r reps] [bescmd ...]"
+	exit 2
+fi
+
+set -- $args
+
+for i
+do
+    case "$i"
+    in
+        -r)
+            reps=$2; shift;
+            shift;;
+        --)
+        	shift; break;;
+    esac
+done
+
+# now process all of the bescmd files...
 
 for command in $@
 do
-
-
     logFile=$command".log"
     resultFile=$command".result"
- 
     
-    rm -f $logFile $resultFile
-    
+    rm -f $logFile $resultFile 2>/dev/null
 
-    # repCount=$(($reps-1))
     repCount=0
     
     while [ $repCount -lt $reps ]
     do
-        #echo "Processing command " $command " repCount: " $repCount
-        #besstandalone -r $reps -c $prefix/etc/bes/bes.conf -d "cerr,timing,h5,h4,ncml" -i $command > $resultFile 2>>$logFile
         besstandalone -c $prefix/etc/bes/bes.conf -d "cerr,timing,ncml" -i $command > $resultFile 2>>$logFile
         repCount=$[repCount + 1] 
-        #ls -l $logFile
     done
     
     runs=`grep ELAPSED $logFile |  grep -E "get (dds|das|dods|dmr|dap)" | wc | awk '{print $1;}' -`
     
-    # echo runs: $runs
     if [ $runs != $reps ]; then
         echo "ERROR: Failed to complete all scheduled reps of command $command. Skipping results."
     else 
-    
-            
         times=`grep ELAPSED $logFile |  grep -E "get (dds|das|dods|dmr|dap)" | awk '{ split($0,s,"["); print s[10];}' - | sed "s/]//g"`
-        
-        # echo "times: "$times
-        
-        # metrics=`echo $times | awk 'BEGIN{sum=0;}{ for(i=1; i<=NF ;i++){sum=sum+$i;} print sum, sum/NF;}' -`
-        
         
         metrics=`echo $times | awk '{for(i=1;i<=NF;i++){sum += $i; sumsq += ($i)^2;}}END {printf("%f %f \n", sum/NF, sqrt((sumsq-sum^2/NF)/NF))}' -`
         
@@ -48,11 +67,4 @@ do
     
         echo "$command: $avg ms (+/- $stdev ms) avg time for "$reps" reps."
     fi
-    
 done
-
-
-
-
-
-
